DROP SCHEMA PUBLIC CASCADE

create table recipes(
id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
name varchar(255),
author varchar(50),
guide varchar(4000)
);

create table ingredients(
recipe_id integer,
ingredient varchar(100),
quantity varchar(50)
);